from __future__ import annotations

import re
import subprocess
from pathlib import Path

from src.project_cli import COMMANDS

PROJECT_ROOT = Path(__file__).resolve().parents[1]

SEMANTIC_VERIFIERS = (
    "src/verification/development_pipeline.py",
    "src/verification/sample_intake_workflow.py",
    "src/verification/first_batch_preparation.py",
    "src/verification/capture_staging.py",
    "src/verification/local_capture_import.py",
    "src/verification/capture_session_readiness.py",
    "src/verification/capture_dashboard.py",
    "src/verification/capture_execution.py",
    "src/verification/review_queue.py",
    "src/verification/manual_decision_workflow.py",
    "src/verification/real_dataset_foundation.py",
    "src/verification/open_license_dataset.py",
    "src/verification/external_dataset_integration.py",
    "src/verification/real_dataset_ingestion.py",
    "src/verification/integrated_training_validation.py",
    "src/verification/validation_model_improvement.py",
    "src/verification/final_model_and_evaluation_protocol.py",
    "src/verification/final_exam_notebook.py",
)

OLD_COMMANDS = (
    "verify-" + "step-008-2",
    "verify-" + "step-009-1",
    "verify-" + "step-009-2",
    "verify-" + "step-009-3",
    "verify-" + "step-009-4",
    "verify-" + "step-009-5",
    "verify-" + "step-009-6",
    "verify-" + "step-009-7",
    "verify-" + "step-009-8",
    "verify-" + "step-009-9",
    "verify-" + "step-009",
    "verify-" + "step-010-1",
    "verify-" + "step-010-2",
    "verify-" + "step-010",
)

NEW_COMMANDS = (
    "verify-development-pipeline",
    "verify-sample-intake",
    "verify-first-batch-preparation",
    "verify-capture-staging",
    "verify-local-capture-import",
    "verify-capture-session",
    "verify-capture-dashboard",
    "verify-capture-execution",
    "verify-review-queue",
    "verify-manual-decisions",
    "verify-real-dataset-foundation",
    "verify-open-license-dataset",
    "verify-external-dataset-integration",
    "verify-real-dataset-ingestion",
    "verify-integrated-training-validation",
    "verify-validation-model-improvement",
    "verify-final-model-freeze",
    "verify-final-exam-notebook",
)

TEXT_EXTENSIONS = {
    ".py",
    ".md",
    ".txt",
    ".json",
    ".csv",
    ".html",
    ".yml",
    ".yaml",
    ".toml",
    ".ipynb",
}


def repository_files() -> list[Path]:
    result = subprocess.run(
        [
            "git",
            "ls-files",
            "-c",
            "-o",
            "--exclude-standard",
            "-z",
        ],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )

    return [
        path
        for relative in result.stdout.split("\0")
        if relative
        for path in (PROJECT_ROOT / relative,)
        if path.exists()
    ]


def test_semantic_verifier_modules_exist() -> None:
    for relative_path in SEMANTIC_VERIFIERS:
        assert (PROJECT_ROOT / relative_path).is_file()


def test_legacy_verifier_names_are_absent() -> None:
    legacy_path_token = "verify_" + "step_"

    for path in repository_files():
        relative = path.relative_to(PROJECT_ROOT).as_posix()
        assert legacy_path_token not in relative
        assert re.search(
            r"(?:^|/)step_[0-9]",
            relative,
            flags=re.IGNORECASE,
        ) is None


def test_cli_uses_semantic_verifier_commands() -> None:
    for command in OLD_COMMANDS:
        assert command not in COMMANDS

    for command in NEW_COMMANDS:
        assert command in COMMANDS
        assert COMMANDS[command].module.startswith(
            "src.verification."
        )

    assert "verify-project" in COMMANDS
    assert COMMANDS["verify-project"].module == (
        "src.verification.project_verification"
    )


def test_repository_has_no_delivery_artifacts() -> None:
    for path in repository_files():
        name = path.name.lower()
        suffix = path.suffix.lower()

        assert not (
            suffix in {".ps1", ".cmd", ".bat", ".zip"}
            and (
                name.startswith("apply_")
                or "patch" in name
                or "hotfix" in name
            )
        )

        assert "patch_manifest" not in name
        assert "clean_zip_manifest" not in name
        assert "full_clean_checkpoint" not in name


def test_repository_has_no_assistance_or_local_path_markers() -> None:
    marker_parts = (
        ("chat", "gpt"),
        ("open", "ai"),
        ("anthro", "pic"),
        ("clau", "de"),
        ("google ", "gemini"),
        ("github ", "copilot"),
        ("ai-", "generated"),
        ("generated by ", "ai"),
        ("assistant-", "generated"),
        ("large language ", "model"),
        ("language model ", "assistance"),
    )
    markers = tuple(
        (left + right).lower()
        for left, right in marker_parts
    )

    package_parts = (
        ("patch_", "manifest"),
        ("hotfix_", "step"),
        ("apply_", "step"),
        ("clean_zip_", "manifest"),
        ("full_clean_", "checkpoint"),
    )
    package_markers = tuple(
        (left + right).lower()
        for left, right in package_parts
    )

    for path in repository_files():
        if (
            not path.is_file()
            or path.suffix.lower() not in TEXT_EXTENSIONS
            or path.name == "test_repository_hygiene.py"
        ):
            continue

        try:
            text = path.read_text(
                encoding="utf-8-sig"
            ).lower()
        except UnicodeDecodeError:
            continue

        for marker in markers:
            assert marker not in text

        for marker in package_markers:
            assert marker not in text

        separator_pattern = (
            "(?:"
            + re.escape(chr(92))
            + "+|/+)"
        )
        windows_user_pattern = re.compile(
            "(?i)c:"
            + separator_pattern
            + "users"
            + separator_pattern
            + "stana"
            + separator_pattern
        )
        temporary_root_pattern = re.compile(
            "(?i)/"
            + "mnt"
            + "/"
            + "data"
            + "/"
        )

        assert windows_user_pattern.search(text) is None
        assert temporary_root_pattern.search(text) is None
