from __future__ import annotations

from src.dataset_config import LABELS
from src.integrated_training_config import (
    BATCH_SIZE,
    EARLY_STOPPING_PATIENCE,
    IMAGE_HEIGHT,
    IMAGE_WIDTH,
    INTEGRATED_ARCHITECTURE_PATHS,
    INTEGRATED_METRIC_PATHS,
    INTEGRATED_RUN_STATUS_PATH,
    INTEGRATED_TEST_LOCK_PATH,
    INTEGRATED_TRAIN_PATH,
    INTEGRATED_VALIDATION_PATH,
    LOCKED_TEST_PATHS,
    MAX_EPOCHS,
    RANDOM_STATE,
    TEXT_EMBEDDING_DIMENSION,
    TEXT_SEQUENCE_LENGTH,
)
from src.real_dataset_config import PROJECT_ROOT
from src.validation_model_improvement_config import (
    EXPERIMENT_REGISTRY_PATH,
    SELECTION_DECISION_PATH,
    VALIDATION_IMPROVEMENT_STATUS_PATH,
)

FINAL_MODEL_FREEZE_ROOT = PROJECT_ROOT / "reports" / "final_model_freeze"
FINAL_MODEL_SPECIFICATION_PATH = (
    FINAL_MODEL_FREEZE_ROOT / "final_model_specification.json"
)
FINAL_EVALUATION_PROTOCOL_PATH = (
    FINAL_MODEL_FREEZE_ROOT / "final_evaluation_protocol.json"
)
LOCKED_TEST_CONTRACT_PATH = (
    FINAL_MODEL_FREEZE_ROOT / "locked_test_contract.json"
)
FINAL_TEST_AUTHORIZATION_PATH = (
    FINAL_MODEL_FREEZE_ROOT / "final_test_authorization.json"
)
FINAL_MODEL_FREEZE_MANIFEST_PATH = (
    FINAL_MODEL_FREEZE_ROOT / "final_model_freeze_manifest.json"
)
FINAL_MODEL_FREEZE_SUMMARY_PATH = (
    FINAL_MODEL_FREEZE_ROOT
    / "final_model_and_locked_test_evaluation_protocol_summary.md"
)
FINAL_MODEL_FREEZE_STATUS_PATH = (
    FINAL_MODEL_FREEZE_ROOT / "final_model_freeze_status.json"
)

FINAL_MODEL_SLUG = "keras_multimodal"
FINAL_MODEL_TITLE = "Keras Multimodal Neural Network"
FINAL_MODEL_FAMILY = "reference_multimodal"
EXPECTED_SELECTION_DECISION = "REFERENCE_RETAINED"
SELECTION_CHECKPOINT_COMMIT = "be7a3fb"
FREEZE_READINESS = "FINAL_MODEL_AND_EVALUATION_PROTOCOL_FROZEN_TEST_LOCKED"

FINAL_MODEL_ARCHITECTURE_PATH = INTEGRATED_ARCHITECTURE_PATHS[FINAL_MODEL_SLUG]
FINAL_MODEL_VALIDATION_METRICS_PATH = INTEGRATED_METRIC_PATHS[FINAL_MODEL_SLUG]
REQUIREMENTS_LOCK_PATH = PROJECT_ROOT / "requirements-lock.txt"

FINAL_EVALUATION_METRICS = (
    "accuracy",
    "macro_precision",
    "macro_recall",
    "macro_f1",
    "per_class_precision_recall_f1_support",
    "confusion_matrix",
    "per_category_accuracy_and_macro_f1",
    "per_source_accuracy_and_macro_f1",
    "prediction_ledger",
)

FROZEN_LABEL_ORDER = tuple(LABELS)
FROZEN_RANDOM_STATE = RANDOM_STATE
FROZEN_IMAGE_HEIGHT = IMAGE_HEIGHT
FROZEN_IMAGE_WIDTH = IMAGE_WIDTH
FROZEN_TEXT_SEQUENCE_LENGTH = TEXT_SEQUENCE_LENGTH
FROZEN_TEXT_EMBEDDING_DIMENSION = TEXT_EMBEDDING_DIMENSION
FROZEN_BATCH_SIZE = BATCH_SIZE
FROZEN_MAX_EPOCHS = MAX_EPOCHS
FROZEN_EARLY_STOPPING_PATIENCE = EARLY_STOPPING_PATIENCE
FROZEN_TRAINING_INPUTS = (INTEGRATED_TRAIN_PATH, INTEGRATED_VALIDATION_PATH)
FROZEN_LOCKED_TEST_PATHS = tuple(LOCKED_TEST_PATHS)
